// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUebe2JDnqvql7-D9lHcD-8rhgp6J1xVk',
    appId: '1:302932622142:web:e3e6c0adcf685c05fb4a6f',
    messagingSenderId: '302932622142',
    projectId: 'shabika-50d76',
    authDomain: 'shabika-50d76.firebaseapp.com',
    storageBucket: 'shabika-50d76.appspot.com',
    measurementId: 'G-WMPXXM9MYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6G1qq6YWM7BeG1QD2MJtOyf5ikn3R1Rg',
    appId: '1:302932622142:android:a585ca8b80bed8a3fb4a6f',
    messagingSenderId: '302932622142',
    projectId: 'shabika-50d76',
    storageBucket: 'shabika-50d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnhnJNbeFgIavKIj3SZBS4IxhpFwvPZpg',
    appId: '1:302932622142:ios:48c552475e34a738fb4a6f',
    messagingSenderId: '302932622142',
    projectId: 'shabika-50d76',
    storageBucket: 'shabika-50d76.appspot.com',
    iosClientId: '302932622142-73poegn8btnisc1930qvj3gho8ap0vul.apps.googleusercontent.com',
    iosBundleId: 'com.bru.cons.mobile2',
  );
}
